FROM nginx:1.10.0-alpine

MAINTAINER Jordan Schatz <jordan@noionlabs.com>

COPY dockerfiles/nginx/conf/nginx.conf /etc/nginx/nginx.conf

COPY dockerfiles/nginx/conf/default.conf /etc/nginx/conf.d/default.conf

