reaction:
  image: reactioncommerce/reaction:latest
  restart: always
  ports:
    - "3000:3000"
  environment:
    ROOT_URL: "http://rc.noionlabs.com"
    MONGO_URL: "mongodb://rc.db.svc.5c9d7846-2256-c131-8d57-8f06c078f2ad.us-sw-1.cns.joyent.com:27017/reaction"
    REACTION_EMAIL: "test@test.com"
    REACTION_USER: "admin"
    REACTION_AUTH: "password"
  labels:
    com.joyent.package: g4-highcpu-512M
    triton.cns.services: rc.rc

mongo:
  image: mongo:latest
  restart: always
  command: mongod --storageEngine=wiredTiger
  labels:
    com.joyent.package: g4-highcpu-128M
    triton.cns.services: rc.db

proxy:
  build: dockerfiles/nginx
  restart: always
  ports:
    - "80:80"
  labels:
    com.joyent.package: g4-highcpu-128M
    triton.cns.services: rc.proxy
